
//import GUI.*;
//import contactlist.ContactList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadat
 */
public class AddNewContactGUI extends javax.swing.JFrame {
    int selectedDateRow=-1, selectedPhoneRow=-1, selectedAddressRow=-1;
    /**
     * Creates new form AddNewContactGUI2
     */
    public AddNewContactGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fnameTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mnameTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dateTable = new javax.swing.JTable();
        dateTf = new javax.swing.JLabel();
        addNewDateBtn = new javax.swing.JButton();
        deleteDateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        addNewAddressBtn = new javax.swing.JButton();
        deleteAddressBtn = new javax.swing.JButton();
        addNewPhoneBtn = new javax.swing.JButton();
        deletePhoneBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        phoneTable = new javax.swing.JTable();
        saveContactBtn = new javax.swing.JButton();

        saveBtn.setText("save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD NEW CONTACT");
        setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        jLabel1.setText("First Name");

        jLabel2.setText("Middle Name");

        mnameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameTfActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name");

        dateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Type", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dateTable);

        dateTf.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        dateTf.setText("DATES");

        addNewDateBtn.setText("Add New Date");
        addNewDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDateBtnActionPerformed(evt);
            }
        });

        deleteDateBtn.setText("Delete Row");
        deleteDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDateBtnActionPerformed(evt);
            }
        });

        addressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address Type", "Address", "City", "State", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        addressTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addressTable);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setText("ADDRESSES");

        addNewAddressBtn.setText("Add New Address");
        addNewAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAddressBtnActionPerformed(evt);
            }
        });

        deleteAddressBtn.setText("Delete Row");
        deleteAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAddressBtnActionPerformed(evt);
            }
        });

        addNewPhoneBtn.setText("Add New Phone");
        addNewPhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPhoneBtnActionPerformed(evt);
            }
        });

        deletePhoneBtn.setText("Delete Row");
        deletePhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePhoneBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setText("PHONES");

        phoneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone Type", "Area Code", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phoneTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(phoneTable);

        saveContactBtn.setText("Save Contact");
        saveContactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveContactBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(470, 470, 470))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewAddressBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addNewDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletePhoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewPhoneBtn))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(saveContactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(fnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(mnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addGap(18, 18, 18)
                    .addComponent(lnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(dateTf)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addNewDateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteDateBtn)))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(addNewAddressBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAddressBtn)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(addNewPhoneBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletePhoneBtn)))
                .addGap(63, 63, 63)
                .addComponent(saveContactBtn)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(fnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(lnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addContainerGap(565, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameTfActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        /*
        String fname = fnameTf.getText();
        String mname = mnameTf.getText();
        String lname = lnameTf.getText();
        ContactList list = new ContactList();
        list.updateName(this.contactId,fname,mname,lname);
        dispose();
        */
    }//GEN-LAST:event_saveBtnActionPerformed

    private void dateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTableMouseClicked
        // TODO add your handling code here:
        selectedDateRow = dateTable.getSelectedRow();  
        
    }//GEN-LAST:event_dateTableMouseClicked

    private void addNewDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDateBtnActionPerformed
        // TODO add your handling code here:
        AddNewDateGUI addNewDate = new AddNewDateGUI();
        addNewDate.setVisible(true); 
        addNewDate.pack();
        addNewDate.setLocationRelativeTo(null);
        addNewDate.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addNewDateBtnActionPerformed

    /**
     *
     * @param dateType
     * @param date
     */
    public static void addDateRow(String dateType, String date){
        DefaultTableModel tm = (DefaultTableModel)dateTable.getModel();
        
        Object[] row = new Object[2];
        row[0] = dateType;
        row[1] = date;
        tm.addRow(row);
    }
    
    public static void deleteRow(String tableName,int row){
       if(tableName == "date"){
         DefaultTableModel tm = (DefaultTableModel)dateTable.getModel();
         tm.removeRow(row);
        }
       if(tableName == "phone"){
         DefaultTableModel tm = (DefaultTableModel)phoneTable.getModel();
         tm.removeRow(row);
        }
       if(tableName == "address"){
         DefaultTableModel tm = (DefaultTableModel)addressTable.getModel();
         tm.removeRow(row);
        }
    }
    
    private void deleteDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDateBtnActionPerformed
        // TODO add your handling code here:
        if(selectedDateRow ==-1){
            JOptionPane.showMessageDialog(this, "Please select a date");
        }
        else{
            deleteRow("date",selectedDateRow);
        }
        
    }//GEN-LAST:event_deleteDateBtnActionPerformed

    private void addressTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTableMouseClicked
        // TODO add your handling code here:
        selectedAddressRow = addressTable.getSelectedRow();  
        
    }//GEN-LAST:event_addressTableMouseClicked

    private void addNewAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAddressBtnActionPerformed
        // TODO add your handling code here:
        AddNewAddressGUI addNewAddress = new AddNewAddressGUI();
        addNewAddress.setVisible(true); 
        addNewAddress.pack();
        addNewAddress.setLocationRelativeTo(null);
        addNewAddress.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addNewAddressBtnActionPerformed
    
    public static void addAddressRow(String addressType, String address, String city, String state, String zipcode){
        DefaultTableModel tm = (DefaultTableModel)addressTable.getModel();
        
        Object[] row = new Object[5];
        row[0] = addressType;
        row[1] = address;
        row[2] = city;
        row[3] = state;
        row[4] = zipcode;
        
        tm.addRow(row);
    }
    
    private void deleteAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAddressBtnActionPerformed
        // TODO add your handling code here:
        if(selectedAddressRow ==-1){
            JOptionPane.showMessageDialog(this, "Please select an address");
        }
        else{
            deleteRow("address",selectedAddressRow);
        }
                
    }//GEN-LAST:event_deleteAddressBtnActionPerformed

    private void addNewPhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPhoneBtnActionPerformed
        // TODO add your handling code here:
        AddNewPhoneGUI addNewPhone = new AddNewPhoneGUI();
        addNewPhone.setVisible(true); 
        addNewPhone.pack();
        addNewPhone.setLocationRelativeTo(null);
        addNewPhone.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addNewPhoneBtnActionPerformed
    
    public static void addPhoneRow(String phoneType, String areaCode, String number){
        DefaultTableModel tm = (DefaultTableModel)phoneTable.getModel();
        
        Object[] row = new Object[3];
        row[0] = phoneType;
        row[1] = areaCode;
        row[2] = number;
        
        tm.addRow(row);
    }
    
    private void deletePhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePhoneBtnActionPerformed
        // TODO add your handling code here:
        if(selectedPhoneRow ==-1){
            JOptionPane.showMessageDialog(this, "Please select a phone");
        }
        else{
            deleteRow("phone",selectedPhoneRow);
        }
        
    }//GEN-LAST:event_deletePhoneBtnActionPerformed

    private void phoneTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneTableMouseClicked
        // TODO add your handling code here:
        selectedPhoneRow = phoneTable.getSelectedRow();
        
        /*
        int row = phoneTable.getSelectedRow();
        this.phoneId = phoneTable.getModel().getValueAt(row, 0).toString();
        this.phoneType = phoneTable.getModel().getValueAt(row, 1).toString();
        this.areaCode = phoneTable.getModel().getValueAt(row, 2).toString();
        this.number = phoneTable.getModel().getValueAt(row, 3).toString();
        */
    }//GEN-LAST:event_phoneTableMouseClicked

    private void saveContactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveContactBtnActionPerformed
        // TODO add your handling code here:
        String text = fnameTf.getText();
        if(text.isEmpty()){
            JOptionPane.showMessageDialog(null, "First name can't be null");
        }
        else{
            String fname = fnameTf.getText();
            String mname = mnameTf.getText();
            String lname = lnameTf.getText();

            int dateRowCount = dateTable.getRowCount();
            String[][] dateArray = new String[dateRowCount][2];

            for(int i=0; i<dateRowCount; i++){
                dateArray[i][0] = dateTable.getModel().getValueAt(i, 0).toString();
                dateArray[i][1] = dateTable.getModel().getValueAt(i, 1).toString();
            }

            int addressRowCount = addressTable.getRowCount();
            String[][] addressArray = new String[addressRowCount][5];

            for(int i=0; i<addressRowCount; i++){
                addressArray[i][0] = addressTable.getModel().getValueAt(i, 0).toString();
                addressArray[i][1] = addressTable.getModel().getValueAt(i, 1).toString();
                addressArray[i][2] = addressTable.getModel().getValueAt(i, 2).toString();
                addressArray[i][3] = addressTable.getModel().getValueAt(i, 3).toString();
                addressArray[i][4] = addressTable.getModel().getValueAt(i, 4).toString();
            }

            int phoneRowCount = phoneTable.getRowCount();
            String[][] phoneArray = new String[phoneRowCount][3];

            for(int i=0; i<phoneRowCount; i++){
                phoneArray[i][0] = phoneTable.getModel().getValueAt(i, 0).toString();
                phoneArray[i][1] = phoneTable.getModel().getValueAt(i, 1).toString();
                phoneArray[i][2] = phoneTable.getModel().getValueAt(i, 2).toString();
            }

            ContactList list = new ContactList();
            list.addContact(fname, mname, lname, dateArray, addressArray, phoneArray);
            ContactListGUI.selectedRow =-1;
            ContactListGUI.displayContacts();
            dispose();

        }
        
    }//GEN-LAST:event_saveContactBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewContactGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewAddressBtn;
    private javax.swing.JButton addNewDateBtn;
    private javax.swing.JButton addNewPhoneBtn;
    private static javax.swing.JTable addressTable;
    private static javax.swing.JTable dateTable;
    private javax.swing.JLabel dateTf;
    private javax.swing.JButton deleteAddressBtn;
    private javax.swing.JButton deleteDateBtn;
    private javax.swing.JButton deletePhoneBtn;
    private javax.swing.JTextField fnameTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lnameTf;
    private javax.swing.JTextField mnameTf;
    private static javax.swing.JTable phoneTable;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton saveContactBtn;
    // End of variables declaration//GEN-END:variables
}
