
//import GUI.*;
//import GUI.EditContactGUI;
//import static ContactList.inRange;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import contactlist.connector;
import java.sql.ResultSet;
//import contactlist.ContactList;
//import static contactlist.ContactList.inRange;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadat
 */
public class EditAddDateGUI extends javax.swing.JFrame {
    String dateType, date;
    int contact_id;
    /**
     * Creates new form EditAddDateGUI
     */
    public EditAddDateGUI() {
        initComponents();
    }
    public EditAddDateGUI(int contact_id) {
        this.contact_id = contact_id;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateTypeTf = new javax.swing.JTextField();
        dateTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addNewDateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date Type");

        jLabel2.setText("Date");

        addNewDateBtn.setText("Add Date");
        addNewDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDateBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("format:  'yyyy-mm-dd'");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(addNewDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(addNewDateBtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDateBtnActionPerformed
        // TODO add your handling code here:

        String checkDate = dateTf.getText();
        
        try{
            if(checkDate.length()!=10){
                JOptionPane.showMessageDialog(null, "length of date is not according to format 'yyyy-mm-dd'");
            }
            else{
                String year = checkDate.substring(0, 4);
                String month = checkDate.substring(5, 7);
                String day = checkDate.substring(8);
                String hypenChar1 = checkDate.substring(4,5);
                String hypenChar2 = checkDate.substring(7,8);

                if(!ContactList.isNumeric(year)||!ContactList.isNumeric(month)||!ContactList.isNumeric(day)){
                    JOptionPane.showMessageDialog(null, "year, month and date must be numeric");
                }
                else if(!hypenChar1.equals("-")|| !hypenChar2.equals("-")){
                    JOptionPane.showMessageDialog(null, "seperation character must be '-'");
                }
                else if(year.length()!=4||month.length()!=2||day.length()!=2){
                    JOptionPane.showMessageDialog(null, "length of date is not according to format 'yyyy-mm-dd'");
                }
                else if(ContactList.inRange(01,12, Integer.parseInt(month)) == false || ContactList.inRange(01,31, Integer.parseInt(day)) == false ){

                    JOptionPane.showMessageDialog(null, "Date or month is out of range");
                }
                else{
                    this.dateType = dateTypeTf.getText();
                    this.date = dateTf.getText();

                    Connection con = connector.get();
                    String sqlDate = "insert into date (contact_id,date_type, date) values (?,?,?)";
                    PreparedStatement psDate = con.prepareStatement(sqlDate);

                    psDate.setInt(1, this.contact_id);
                    psDate.setString(2, this.dateType);//dateType
                    psDate.setString(3, this.date);//date
                    psDate.execute();
                    
                        
               
                    
                    String sqlDate2 = "select * from date where contact_id = '"+this.contact_id+"' AND date_type = '"+this.dateType+"' AND date = '"+this.date+"'";
                    PreparedStatement psDate2 = con.prepareStatement(sqlDate2);
                    ResultSet rsDate = psDate2.executeQuery();
                    String dateId = null;
                     while(rsDate.next())
                    {
                        dateId = String.valueOf(rsDate.getInt("Date_id"));
                    }
                    EditContactGUI.editAddDateRow(dateId, this.dateType, this.date);
                    dispose();
                }
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addNewDateBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAddDateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAddDateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAddDateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAddDateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAddDateGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewDateBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField dateTf;
    private javax.swing.JTextField dateTypeTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
