


//import GUI.*;
//import GUI.AddNewContactGUI;
//import GUI.EditContactGUI;
//import contactlist.ContactList;
//import contactlist.connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadat
 */
public class EditAddAddressGUI extends javax.swing.JFrame {
    String addressType, address, city, state, zipcode;
    int contact_id;
    /**
     * Creates new form EditAddAddressGUI
     */
    public EditAddAddressGUI() {
        initComponents();
    }
    public EditAddAddressGUI(int contact_id) {
        this.contact_id = contact_id;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addressTypeTf = new javax.swing.JTextField();
        addressTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        stateTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cityTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zipcodeTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addAddressBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Address Type");

        addressTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTypeTfActionPerformed(evt);
            }
        });

        addressTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTfActionPerformed(evt);
            }
        });

        jLabel2.setText("Address");

        stateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTfActionPerformed(evt);
            }
        });

        jLabel3.setText("City");

        cityTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTfActionPerformed(evt);
            }
        });

        jLabel4.setText("State");

        zipcodeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeTfActionPerformed(evt);
            }
        });

        jLabel5.setText("Zipcode");

        jLabel6.setText("format: '6-digit numeric'");

        addAddressBtn.setText("save");
        addAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addressTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(stateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(addAddressBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTypeTfActionPerformed

    private void addressTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTfActionPerformed

    private void stateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTfActionPerformed

    private void cityTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTfActionPerformed

    private void zipcodeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeTfActionPerformed

    private void addAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(!ContactList.isNumeric(zipcodeTf.getText())){
            JOptionPane.showMessageDialog(null, "Zipcode must be numeric");
        }
        else if(zipcodeTf.getText().length() != 6){
            JOptionPane.showMessageDialog(null, "Zipcode must be 6-digit");
        }
        else{
            this.addressType = addressTypeTf.getText();
            this.address = addressTf.getText();
            this.city = cityTf.getText();
            this.state = stateTf.getText();
            this.zipcode = zipcodeTf.getText();
            
            Connection con = connector.get();
            String sqlAddress = "insert into address (contact_id, Address_type, Address, City, State, Zip) values (?,?,?,?,?,?)";
            PreparedStatement psAddress = con.prepareStatement(sqlAddress);

            psAddress.setInt(1, this.contact_id);
            psAddress.setString(2, this.addressType);//dateType
            psAddress.setString(3, this.address);//date
            psAddress.setString(4, this.city);//dateType
            psAddress.setString(5, this.state);//date
            psAddress.setString(6, this.zipcode);//dateType
            
            psAddress.execute();




            String sqlAddress2 = "select * from address where contact_id = '"+this.contact_id+"' AND Address_type = '"+this.addressType+"' AND address = '"+this.address+"' AND city = '"+this.city+"' AND state = '"+this.state+"' AND zip = '"+this.zipcode+"'";
            PreparedStatement psAddress2 = con.prepareStatement(sqlAddress2);
            ResultSet rsAddress = psAddress2.executeQuery();
            String addressId = null;
             while(rsAddress.next())
            {
                addressId = String.valueOf(rsAddress.getInt("Address_id"));
            }
            EditContactGUI.editAddAddress(addressId,this.addressType, this.address, this.city, this.state, this.zipcode);
            dispose();
        }
        
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_addAddressBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAddAddressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAddAddressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAddAddressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAddAddressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAddAddressGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAddressBtn;
    private javax.swing.JTextField addressTf;
    private javax.swing.JTextField addressTypeTf;
    private javax.swing.JTextField cityTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField stateTf;
    private javax.swing.JTextField zipcodeTf;
    // End of variables declaration//GEN-END:variables
}
