/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import GUI.*;
//import contactlist.ContactList;
//import contactlist.connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nadat
 */
public class EditAddPhoneGUI extends javax.swing.JFrame {
    int contact_id;
    String phoneType, areaCode, number;
    /**
     * Creates new form EditAddPhoneGUI
     */
    public EditAddPhoneGUI() {
        initComponents();
    }
    
    public EditAddPhoneGUI(int contact_id) {
        this.contact_id = contact_id;
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneTypeTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        areaCodeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editAddPhoneBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phoneTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTypeTfActionPerformed(evt);
            }
        });

        jLabel1.setText("Phone Type");

        areaCodeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCodeTfActionPerformed(evt);
            }
        });

        jLabel2.setText("Area Code");

        jLabel4.setText("format: 'must be 3-digit numeric'");

        numberTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTfActionPerformed(evt);
            }
        });

        jLabel3.setText("Number");

        jLabel5.setText("format: 'must be 7-digit numeric'");

        editAddPhoneBtn.setText("Add Phone");
        editAddPhoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddPhoneBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(phoneTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areaCodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberTf, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editAddPhoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaCodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(53, 53, 53)
                .addComponent(editAddPhoneBtn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTypeTfActionPerformed

    private void areaCodeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCodeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaCodeTfActionPerformed

    private void numberTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTfActionPerformed

    private void editAddPhoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddPhoneBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(!ContactList.isNumeric(areaCodeTf.getText())){
                JOptionPane.showMessageDialog(null, "Areacode must be numeric");
            }
            else if(areaCodeTf.getText().length() != 3){
                JOptionPane.showMessageDialog(null, "Areacode must be 3-digit");
            }
            else if(!ContactList.isNumeric(numberTf.getText())){
                JOptionPane.showMessageDialog(null, "Number must be numeric");
            }
            else if(numberTf.getText().length() != 7){
                JOptionPane.showMessageDialog(null, "Number must be 7-digit");
            }
            else{
                this.phoneType = phoneTypeTf.getText();
                this.areaCode = areaCodeTf.getText();
                this.number = numberTf.getText();
                
                
                Connection con = connector.get();
                String sqlPhone = "insert into phone (contact_id, Phone_type, Area_code, Number) values (?,?,?,?)";
                PreparedStatement psPhone = con.prepareStatement(sqlPhone);

                psPhone.setInt(1, this.contact_id);
                psPhone.setString(2, this.phoneType);
                psPhone.setString(3, this.areaCode);
                psPhone.setString(4, this.number);
                psPhone.execute();

                String sqlPhone2 = "select * from phone where contact_id = '"+this.contact_id+"' AND Phone_type = '"+this.phoneType+"' AND Area_code = '"+this.areaCode+"' AND Number = '"+this.number+"'";
                PreparedStatement psPhone2 = con.prepareStatement(sqlPhone2);
                ResultSet rsPhone = psPhone2.executeQuery();
                String phoneId = null;
                 while(rsPhone.next())
                {
                    phoneId = String.valueOf(rsPhone.getInt("Phone_id"));
                }
                EditContactGUI.editAddPhone(phoneId, this.phoneType, this.areaCode, this.number);
                
                dispose();
            }
        }
     catch(Exception e){
         e.printStackTrace();
     }   
    }//GEN-LAST:event_editAddPhoneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAddPhoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAddPhoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAddPhoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAddPhoneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAddPhoneGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaCodeTf;
    private javax.swing.JButton editAddPhoneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField numberTf;
    private javax.swing.JTextField phoneTypeTf;
    // End of variables declaration//GEN-END:variables
}
