
//import GUI.*;
//import GUI.EditContactGUI;
//import contactlist.ContactList;
//import contactlist.connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadat
 */
public class EditDateRowGUI extends javax.swing.JFrame {
    String  dateId, dateType, date;
    int rowId;
    /**
     * Creates new form EditDateRow
     */
    public EditDateRowGUI() {
        initComponents();
        
    }
    public EditDateRowGUI(int rowId,String dateId, String dateType, String date){
        this.rowId = rowId;
        this.dateId = dateId;
        this.dateType = dateType;
        this.date = date;
        
        initComponents();
        display();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dateTypeTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateTf = new javax.swing.JTextField();
        cancelDateSaveBtn = new javax.swing.JButton();
        dateSaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Date");

        jLabel1.setText("Date Type");

        dateTypeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTypeTfActionPerformed(evt);
            }
        });

        jLabel2.setText("Date");

        dateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTfActionPerformed(evt);
            }
        });

        cancelDateSaveBtn.setText("Cancel");
        cancelDateSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDateSaveBtnActionPerformed(evt);
            }
        });

        dateSaveBtn.setText("Save");
        dateSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cancelDateSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(dateSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelDateSaveBtn)
                    .addComponent(dateSaveBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTypeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTypeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTypeTfActionPerformed

    private void dateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTfActionPerformed

    private void cancelDateSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDateSaveBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelDateSaveBtnActionPerformed

    private void dateSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSaveBtnActionPerformed
        // TODO add your handling code here:
        
        String checkDate = dateTf.getText();
        String a ="";
        a="";
        try{
            if(checkDate.length()!=10){
                JOptionPane.showMessageDialog(null, "length of date is not according to format 'yyyy-mm-dd'");
            }
            else{
                String year = checkDate.substring(0, 4);
                String month = checkDate.substring(5, 7);
                String day = checkDate.substring(8);
                String hypenChar1 = checkDate.substring(4,5);
                String hypenChar2 = checkDate.substring(7,8);

                if(!ContactList.isNumeric(year)||!ContactList.isNumeric(month)||!ContactList.isNumeric(day)){
                    JOptionPane.showMessageDialog(null, "year, month and date must be numeric");
                }
                else if(!hypenChar1.equals("-")|| !hypenChar2.equals("-")){
                    JOptionPane.showMessageDialog(null, "seperation character must be '-'");
                }
                else if(year.length()!=4||month.length()!=2||day.length()!=2){
                    JOptionPane.showMessageDialog(null, "length of date is not according to format 'yyyy-mm-dd'");
                }
                else if(ContactList.inRange(01,12, Integer.parseInt(month)) == false || ContactList.inRange(01,31, Integer.parseInt(day)) == false ){

                    JOptionPane.showMessageDialog(null, "Date or month is out of range");
                }
                else{

                    String newDateType = dateTypeTf.getText();
                    String newDate = dateTf.getText();
                    
                    //insert date
                    Connection con = connector.get();    
                    String sqlDate = "UPDATE date SET date_type = ?, date = ? WHERE Date_id = ?";
                    PreparedStatement psDate = con.prepareStatement(sqlDate);

                    psDate.setString(1, newDateType);//DateType
                    psDate.setString(2, newDate);//Date
                    psDate.setInt(3, Integer.parseInt(this.dateId));
                    psDate.execute();

                    EditContactGUI.editDateRow(this.rowId,this.dateId, newDateType,  newDate);
                    JOptionPane.showMessageDialog(null, "Date updated successfully");
                    dispose();
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_dateSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDateRowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDateRowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDateRowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDateRowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDateRowGUI().setVisible(true);
            }
        });
    }
    
    public void display(){
        
        dateTypeTf.setText(this.dateType);
        dateTf.setText(this.date);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelDateSaveBtn;
    private javax.swing.JButton dateSaveBtn;
    private javax.swing.JTextField dateTf;
    private javax.swing.JTextField dateTypeTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
